name: Actions Workflow

# on:
#   push:
#      branches-ignore:  # will start in all branches exept master and feauture
#        - master   
#        - 'feature/*' # any feature/a  but not feaure/feat/a 
#________________
# on:
#   push:
#      branches:
#        - master   # will start if you push something to master branch
#        - 'feature/*' # any feature/a  but not feaure/feat/a 
#        - 'feature/**' # any feature/a/b/c
#        - '!feature/featC'  #Even it match to feature branch, with ! we can exclude it from perform it here
#      tags:    # or tags-ignore
#        - v1.*
#      paths:
#        - '**.js'    #  when we will push any JS file workflow will run, and won't run if any others with path
#        - '!**.py'  # exclude path any py scripts won't start
#                     # or paths-ignore (can't be in the same time) for ex -'docs/**'
#_______________
# on:
#   repository_dispatch: # to start the repo on opsramp request
#     types: [build]
 # _____________
# on : pull_request
# on: 
#   schedule:
#     - cron: "5 * * * *"  # minimum every 5 min
#     - cron: "10 * * * *"  # every 6 min
#_________
# on: [push, pull_request]
#________
# on:
#   push:
#   pull_request:
#     types: [closed, assigned, opened, reopened]  # to also start pipeline on other actions

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env}}        # to see from postman json info of the paiload event env
      - name: Checkout
        #uses: actions/checkout@v1 # clone the repo to VM(runner) not always required   ( @v3 or or master  or can be any commit)
        run: |       # if you need to use linux command -> run
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITBUB_REPOSITORY
          echo $GITHUB_WORKSPACE 
          echo "${{ github.token }}"   
      - name: Simple JS Action  
        id: greet
        uses: actions/hello-world-javascript-action@v1 # to start script from github and also rever to v1 or other branch or commit
        with:
           who-to-greet: John # instructions how to use this action on page
      - name: Log Greeting Time
        run: echo "${{ steps.greet.output.time }}" # made by git steps.id(gaved previously to action).outpusts.time( output in action)

  