name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10  # this docker image will be installed on ubuntu,any step will be on image
    steps:
      - name: Log node.js
        run: |
          node -v
          cat /etc/os-release