name: Shell Commands  # name of the pipeline#

on: push # when start pipeline

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python  #on which shell/programm to use, like bash by default
  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash
  
